import { KnowledgeState, SourceAttribution } from "./types";

const defaultAttribution: SourceAttribution = {
  source: "pulled_from_db_schema",
  tooling_notes: "Discovered via SQLAlchemy inspector",
};

export const MOCK_KNOWLEDGE_STATE: KnowledgeState = {
  source_name: "demo_source",
  review_mode: "guided",
  tables: {
    users: {
      table_name: "users",
      review_status: "confirmed",
      domain: "Users & Access",
      role: "core_entity",
      selected: true,
      recommended_selected: true,
      selected_by_default: true,
      review_decision: "selected",
      needs_review: false,
      requires_review: false,
      business_meaning: "Core table for registered platform users.",
      grain: "One row per user account",
      likely_entity: "User",
      important_columns: ["id", "email", "created_at"],
      valid_joins: ["orders", "user_profiles"],
      common_filters: ["active = true", "created_at > last_month"],
      common_business_questions: [
        "How many active users signed up in the last 30 days?",
        "Which users have not placed an order yet?",
      ],
      sensitivity_notes: ["Contains PII (email)"],
      reason_for_classification: "Included because it looks like a core business table with strong supporting signals.",
      classification_reason: "Classified as a core entity because other tables depend on it and it has descriptive identity columns.",
      selection_reason: "Included because it looks like a core business table with strong supporting signals.",
      review_reason: undefined,
      related_tables: ["orders", "user_profiles"],
      impact_score: 0.86,
      business_relevance: 0.84,
      naming_clarity: 0.88,
      graph_connectivity: 0.72,
      confidence: { label: "high", score: 0.9, rationale: ["Validated by standard schema patterns"] },
      attribution: defaultAttribution,
      decision_id: "decision_users",
      decision_status: "user_confirmed",
      decision_actor: "user_confirmed",
      risk_level: "medium",
      policy_reason: "User confirmed the AI recommendation.",
      evidence_refs: ["Included because it is a core business entity."],
      review_debt: false,
      publish_blocker: false,
      needs_acknowledgement: false,
      columns: [
        {
          column_name: "id",
          technical_type: "INTEGER",
          business_meaning: "Internal unique identifier for a user.",
          example_values: ["101", "102", "103"],
          synonyms: ["user_id", "uid"],
          filterable: true,
          displayable: true,
          sensitive: "none",
          confidence: { label: "high", score: 1.0, rationale: ["Primary key"] },
          attribution: defaultAttribution,
          evidence_refs: [],
          review_debt: false,
          publish_blocker: false,
          needs_acknowledgement: false,
        },
        {
          column_name: "email",
          technical_type: "VARCHAR(255)",
          business_meaning: "Primary contact email address.",
          example_values: ["alice@example.com", "bob@work.com"],
          synonyms: ["login", "username"],
          filterable: true,
          displayable: true,
          sensitive: "sensitive",
          confidence: { label: "high", score: 0.95, rationale: ["Format match"] },
          attribution: { source: "inferred_by_system", rationale: "Detected via regex pattern matching" },
          decision_status: "warning_ack_required",
          decision_actor: "rule_default",
          risk_level: "high",
          policy_reason: "High-risk sensitive field still needs acknowledgement before publish.",
          evidence_refs: ["Contains email-like values."],
          review_debt: true,
          publish_blocker: true,
          needs_acknowledgement: true,
        },
      ],
    },
    orders: {
      table_name: "orders",
      review_status: "pending",
      domain: "Trip Operations",
      role: "transaction",
      selected: true,
      recommended_selected: true,
      selected_by_default: true,
      review_decision: "review",
      needs_review: true,
      requires_review: true,
      business_meaning: "Transactional records for sales and subscriptions.",
      grain: "One row per line item purchase",
      important_columns: ["id", "user_id", "status", "amount"],
      valid_joins: ["users", "products"],
      common_filters: ["status = 'completed'", "amount > 0"],
      common_business_questions: ["What is the total revenue for this month?"],
      sensitivity_notes: [],
      reason_for_classification: "Included, but it still needs confirmation because the business role is not fully certain.",
      classification_reason: "Classified as a transaction because it has status and lifecycle columns and joins to core entities.",
      selection_reason: "Included by default because it appears business-relevant.",
      review_reason: "The table looks important, but the role or scope still needs confirmation.",
      related_tables: ["users", "products"],
      impact_score: 0.91,
      business_relevance: 0.88,
      naming_clarity: 0.69,
      graph_connectivity: 0.74,
      confidence: { label: "medium", score: 0.7, rationale: ["Ambiguous mapping for 'status' codes"] },
      attribution: defaultAttribution,
      decision_id: "decision_orders",
      decision_status: "deferred_review",
      decision_actor: "rule_default",
      risk_level: "medium",
      policy_reason: "Medium-risk selection stays provisionally accepted in guided review.",
      evidence_refs: ["Included by default because it appears business-relevant."],
      review_debt: true,
      publish_blocker: false,
      needs_acknowledgement: false,
      columns: [],
    },
  },
  canonical_entities: {},
  enums: {
    "orders.status": [
      { database_value: "0", business_label: "Pending", attribution: { source: "inferred_by_system" } },
      { database_value: "1", business_label: "Completed", attribution: { source: "inferred_by_system" } },
      { database_value: "2", business_label: "Cancelled", attribution: { source: "inferred_by_system" } },
    ],
  },
  business_rules: [],
  glossary: {},
  query_patterns: [],
  unresolved_gaps: [
    {
      gap_id: "gap-users-pk",
      category: "missing_primary_key",
      target_entity: "users",
      description: "Database schema does not explicitly define a primary key for 'users'.",
      suggested_question: "Should I treat 'id' as the unique primary key for the users table?",
      is_blocking: true,
      priority: 1,
      decision_status: "publish_blocked",
      risk_level: "high",
      policy_reason: "Primary key must be confirmed before publish.",
      review_debt: true,
      publish_blocker: true,
      needs_acknowledgement: false,
    },
    {
      gap_id: "gap-orders-status",
      category: "unconfirmed_enum_mapping",
      target_entity: "orders",
      target_property: "status",
      description: "Found low-cardinality codes (0, 1, 2) in status column.",
      suggested_question: "Do these status codes map to Pending, Completed, and Cancelled?",
      is_blocking: false,
      priority: 2,
      decision_status: "deferred_review",
      risk_level: "low",
      policy_reason: "Auto-decided for now and queued for optional later review.",
      review_debt: true,
      publish_blocker: false,
      needs_acknowledgement: false,
    },
  ],
  readiness: {
    is_ready: false,
    continue_ready: true,
    publish_ready: false,
    readiness_percentage: 65.0,
    blocking_gaps_count: 1,
    publish_blockers_count: 1,
    warning_ack_required_count: 1,
    review_debt_count: 2,
    total_gaps_count: 2,
    readiness_notes: ["Missing primary key on core entity 'users' is blocking publish."],
    continue_notes: ["Onboarding can continue with AI-decided defaults and deferred review."],
    publish_notes: ["1 publish blocker still needs confirmation before publish."],
  },
  review_summary: {
    analyzed_table_count: 2,
    selected_count: 2,
    excluded_count: 0,
    review_count: 1,
    high_confidence_count: 1,
    medium_confidence_count: 1,
    low_confidence_count: 0,
    detected_domains: ["Users & Access", "Trip Operations"],
    auto_accepted_count: 0,
    user_confirmed_count: 1,
    user_overridden_count: 0,
    deferred_review_count: 1,
    publish_blocked_count: 0,
    warning_ack_required_count: 1,
    review_debt_count: 2,
  },
  domain_groups: [
    {
      domain: "Trip Operations",
      tables: ["orders"],
      core_tables: ["orders"],
      anchor_tables: ["orders"],
      selected_count: 1,
      excluded_count: 0,
      review_count: 1,
      inferred_business_meaning: "Business area centered on orders.",
      requires_review: true,
      review_reason: "The table looks important, but the role or scope still needs confirmation.",
      confidence: { label: "medium", score: 0.7, rationale: ["1 table(s) in this domain"] },
      review_debt_count: 1,
      publish_blocker_count: 0,
      warning_ack_required_count: 0,
    },
    {
      domain: "Users & Access",
      tables: ["users"],
      core_tables: ["users"],
      anchor_tables: ["users"],
      selected_count: 1,
      excluded_count: 0,
      review_count: 0,
      inferred_business_meaning: "Business area centered on users.",
      requires_review: false,
      review_reason: undefined,
      confidence: { label: "high", score: 0.9, rationale: ["1 table(s) in this domain"] },
      review_debt_count: 1,
      publish_blocker_count: 1,
      warning_ack_required_count: 1,
    },
  ],
  review_queue: [
    {
      table_name: "orders",
      domain: "Trip Operations",
      role: "transaction",
      confidence: { label: "medium", score: 0.7, rationale: ["Ambiguous mapping for 'status' codes"] },
      selected: true,
      open_gap_count: 1,
      reason_for_classification: "Included, but it still needs confirmation because the business role is not fully certain.",
      selection_reason: "Included by default because it appears business-relevant.",
      review_reason: "The table looks important, but the role or scope still needs confirmation.",
      impact_score: 0.91,
      business_relevance: 0.88,
      related_tables: ["users", "products"],
      decision_status: "deferred_review",
      decision_actor: "rule_default",
      risk_level: "medium",
      policy_reason: "Medium-risk table remains provisionally accepted.",
      review_debt: true,
      publish_blocker: false,
      needs_acknowledgement: false,
    },
  ],
  decision_history: [],
  review_debt: [],
};
